version: '3.8'

services:
  data:
    image: mariadb:10.11
    container_name: data
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ../etape2/sql:/docker-entrypoint-initdb.d
    networks:
      - tp3-net

  script:
    build:
      context: ../etape2/php
      dockerfile: Dockerfile
    container_name: script
    volumes:
      - ../etape2/src:/app
    networks:
      - tp3-net
    depends_on:
      - data

  http:
    image: nginx
    container_name: http
    ports:
      - "8080:80"
    volumes:
      - ../etape2/src:/app
      - ../etape2/config:/etc/nginx/conf.d:ro
    networks:
      - tp3-net
    depends_on:
      - script

networks:
  tp3-net:
    driver: bridge
